### ISSUE TITLE
If user does not exist throw custom exception (eg. UserNotFoundexception ) and do the other validations defined on the requirements of last lesson

### ISSUE THREAD

**Issue by giselacostamindera** [DaveLRB/REST_API_DATABASE#1]
https://github.com/DaveLRB/REST_API_DATABASE/blob/dff2e651ae93429c160917498332a53d47d04b2a/users/src/main/java/com/school/users/service/UserService.java#L30

**Comment by DaveLRB** [comment]
Exceptions handled
